//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ringen.Plugin.CsEditor.Resources.LanguageFiles {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DictPluginMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictPluginMain() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ringen.Plugin.CsEditor.Resources.LanguageFiles.DictPluginMain", typeof(DictPluginMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gew. ähnelt.
        /// </summary>
        public static string ActualWeightShort {
            get {
                return ResourceManager.GetString("ActualWeightShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl Zuschauer ähnelt.
        /// </summary>
        public static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        /// </summary>
        public static string BoutDate {
            get {
                return ResourceManager.GetString("BoutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mannschaftskampf ähnelt.
        /// </summary>
        public static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kommentar ähnelt.
        /// </summary>
        public static string EditorComment {
            get {
                return ResourceManager.GetString("EditorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbesetzt muss nicht mehr eingetragen werden. Dies wird dem Protokoll entnommen.
        ///Ist im Feld Schiedsrichter nichts vermerkt, so ist das im Kommentar zu vermerken.
        ///Verspäteter Start und die Pause müssen nicht mehr eingetragen werden. Diese werden den Kämpfen entnommen. ähnelt.
        /// </summary>
        public static string EditorCommentHint {
            get {
                return ResourceManager.GetString("EditorCommentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name des Bearbeiters ähnelt.
        /// </summary>
        public static string EditorName {
            get {
                return ResourceManager.GetString("EditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Punkte Heim ähnelt.
        /// </summary>
        public static string HomePoints {
            get {
                return ResourceManager.GetString("HomePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heimmannschaft ähnelt.
        /// </summary>
        public static string HomeTeamName {
            get {
                return ResourceManager.GetString("HomeTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heim ähnelt.
        /// </summary>
        public static string HomeTeamNameShort {
            get {
                return ResourceManager.GetString("HomeTeamNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veranstalltungsort ähnelt.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kampfstätte ähnelt.
        /// </summary>
        public static string LocationAddress {
            get {
                return ResourceManager.GetString("LocationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Punkte Gast ähnelt.
        /// </summary>
        public static string OpponentPoints {
            get {
                return ResourceManager.GetString("OpponentPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gastmannschaft ähnelt.
        /// </summary>
        public static string OpponentTeamName {
            get {
                return ResourceManager.GetString("OpponentTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gast ähnelt.
        /// </summary>
        public static string OpponentTeamNameShort {
            get {
                return ResourceManager.GetString("OpponentTeamNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protokoll erstellt am {0} {1} Uhr ähnelt.
        /// </summary>
        public static string PdfProtocolFooterHint {
            get {
                return ResourceManager.GetString("PdfProtocolFooterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protokoll für Mannschaftskämpfe im Ringen ähnelt.
        /// </summary>
        public static string PdfProtocolHeadline {
            get {
                return ResourceManager.GetString("PdfProtocolHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} in {1} Min. ähnelt.
        /// </summary>
        public static string PdfProtocolResult {
            get {
                return ResourceManager.GetString("PdfProtocolResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wertungen ähnelt.
        /// </summary>
        public static string PdfProtocolSinglePoints {
            get {
                return ResourceManager.GetString("PdfProtocolSinglePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protokoll {0} {1}: {2} vs. {3} vom {4} ähnelt.
        /// </summary>
        public static string PdfProtocolTitle {
            get {
                return ResourceManager.GetString("PdfProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} mit {1}:{2} ähnelt.
        /// </summary>
        public static string PdfProtocolWinnerLine {
            get {
                return ResourceManager.GetString("PdfProtocolWinnerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schiedsrichter ähnelt.
        /// </summary>
        public static string Referee {
            get {
                return ResourceManager.GetString("Referee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pkt. ähnelt.
        /// </summary>
        public static string TeamPointsShort {
            get {
                return ResourceManager.GetString("TeamPointsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unentschieden ähnelt.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mannschaftsführer ähnelt.
        /// </summary>
        public static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht eindeutig ähnelt.
        /// </summary>
        public static string Undetermined {
            get {
                return ResourceManager.GetString("Undetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Art des Sieges ähnelt.
        /// </summary>
        public static string VictoryType {
            get {
                return ResourceManager.GetString("VictoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bis kg ähnelt.
        /// </summary>
        public static string WeightClass {
            get {
                return ResourceManager.GetString("WeightClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sieger ähnelt.
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass-Nr. ähnelt.
        /// </summary>
        public static string WrestlerId {
            get {
                return ResourceManager.GetString("WrestlerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string WrestlerName {
            get {
                return ResourceManager.GetString("WrestlerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string WrestlerStatus {
            get {
                return ResourceManager.GetString("WrestlerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stilart ähnelt.
        /// </summary>
        public static string WrestlingStyle {
            get {
                return ResourceManager.GetString("WrestlingStyle", resourceCulture);
            }
        }
    }
}
